### ISSUE TITLE
Error while trying to add reference - only after latest update

### ISSUE THREAD

**Issue by mersadk** [dotnet/wcf#2076]
I use VS2017 on Windows 10 and have ASP.NET Core MVC project targeting .NET Framework 4.5.2. After latest release (2017/07/14) I can't add reference because I get following error when trying to open "Microsoft WCF Web Service Reference Provider". 

![vs error](https://user-images.githubusercontent.com/137991/28239286-3a0444d0-6969-11e7-8f4b-ac6b528f3a09.jpg)

**Comment by nagoh** [comment]
Same deal here

**Comment by savachebra** [comment]
And here..

**Comment by Dolphinsimon** [comment]
Me too...

**Comment by Groman123** [comment]
Same here too...

**Comment by chaseWillden** [comment]
I'm getting the same error, please fix

**Comment by macho0001** [comment]
Same here

**Comment by zhenlan** [comment]
Thanks for reporting the issue. We are actively looking into this. We will keep this thread updated when we find more.

**Comment by zhenlan** [comment]
To unblock everyone while we are investigating the root cause, we have reverted our last update to the previous build. Please uninstall Microsoft WCF Web Service Reference Provider from *Tools->Extensions and Updates* in Visual Studio 2017 and reinstall it from [VS Marketplace]( https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService). Again, thanks for reporting the issue and sorry for any inconvenience caused.

**Comment by zhenlan** [comment]
We have identified the root cause of the issue is because one of referenced assemblies in our last release was updated to a higher version that is only available in VS2017 v15.3 Preview. The issue was introduced when we upgraded our build environment to VS 15.3 as we are focusing on improving experience with .NET Core 2.0 projects, which have a minimum requirement of VS 15.3. It’s an oversight the last release does not work in VS 15.2 or earlier anymore. We are working on a fix.

**Comment by Elprogrammador** [comment]
Thanks zhenlan, uninstalling and reinstalling works.

**Comment by chaseWillden** [comment]
Awesome, it works for me too.

**Comment by MarvinNorway** [comment]
Same problem here. Uninstalling and reinstalling does not work for me.
Running version 0.5.10712.1027 on VS Enterprise 2017, Version 15.2 (26430.16).
Thanks.

**Comment by zhenlan** [comment]
We just released an [updated build (0.5.10718.1239)](https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService) with the fix today. It will take care the upgrade and you don't have to uninstall/reinstall anymore.

Sorry for running into this issue and thanks a lot everyone for your support to help us make this product better!

**Comment by westito** [comment]
Still not working for me. Neither on .Net Standard 2.0, neither on 1.4


Error:The solution cannot be built, please try to rebuild the solution and fix any build problems.
Failed adding Microsoft WCF Web Service Reference Provider - Preview to the project.

No other helping message.
