### ISSUE TITLE
WSDL Reference works with traditional "Add Service Reference" but not "Add Connected Service"

### ISSUE THREAD

**Issue by WillRay** [dotnet/wcf#2736]
The following WSDL reference works with the traditional "Add Service Reference" option in a .Net Framework class library, but not with the new "Add Connected Service" option present in a .Net Core class library.

### Steps to Reproduce

1. Create a new .Net Core 2.0 Class Library
2. Select "Add Connected Service", then "Configure WCF Web Service Reference"
3. Add the following value in the URI field: https://ws2.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?wsdl
4. Hit "Go"

### Error Message
> An error occurred while attempting to find services at 'https://ws2.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?WSDL'. CData elements not valid at top level of an XML document. Line 1, position 3

### Error Detail
> Metadata contains a reference that cannot be resolved: 'https://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd'.

It seems like the CDATA reference at the top of https://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd is causing the problem.

Is there a way for me to add this WSDL reference in a .Net Core 2.0 library?

**Comment by Juanmabs22** [comment]
+1
Same problem here.
I've got a similar problem with this url:
http://localizadoroficinas.correos.es/localizadoroficinas/wsdl/

I think that the problem is WCF is not standard SOAP.

The only solutions I found are:
- Use SoapUI and replicate in c# with your own code
- Generate the struct of System.ServiceModel  in a .net framework project, and migrate all you could...
- Create your own wsdl interpreter and share!
- Create a visual studio extension to fix this like WCF at the begging  [VisualStudioWCFConnectedService](https://marketplace.visualstudio.com/items?itemName=erikcai-MSFT.VisualStudioWCFConnectedService)

Thanks.

**Comment by mlacouture** [comment]
Hi @Juanmabs22 
You are hitting a different issue, the tool fails with an error that explains the problem and looks like this:
"Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is only valid for encoded SOAP."
If you have further questions please report a separate issue.
thank you!
Miguel Lacouture

**Comment by OddmarDam** [comment]
Hi.

Will this issue be resolved in a future release ?
I have the same problem.

Works with 4.6 framework but not .net core 2

**Comment by shakeelsadiq** [comment]
I might be missing something but why did this get closed? I'm using VS 2019 Community and it still happening.
