### ISSUE TITLE
Unable to set a proxy address on BasicHttpBinding

### ISSUE THREAD

**Issue by PedroS11** [dotnet/wcf#3395]
My system works behind a company proxy, so for each request I need to set the proxy address on the BasicHttpBinding.

However, it doesn't work and if I test on a scenario where proxy isn't required, it works.

Here is the binding creation.

```
BasicHttpBinding binding = new BasicHttpBinding();
binding.Security.Mode = BasicHttpSecurityMode.Transport;
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
binding.ProxyAddress = new Uri("https://server:port");
binding.UseDefaultWebProxy = false;
```

I'm using dotnet core 2.2, any idea that you can give me?

**Comment by Lxiamail** [comment]
@PedroS11 which version of WCF package that you are using. Can you make sure using latest version (4.5 above) since we have fixed an related issue since then.

**Comment by PedroS11** [comment]
I'm using 4.6
I just created the dotnet core api project, imported via connected services a wsdl. 
When I call the wsdl with the classes generated it works, if i set a proxy it doesn't. Have you tested doing something like this?

**Comment by PedroS11** [comment]
I tried the 4.5.3 version and I'm still having the same issues. Is it possible to provide a working example? Or a any idea that you can have?

**Comment by Lxiamail** [comment]
@PedroS11 Does the same program works on  full .NET Framework? Can you provide a repro problem?

**Comment by PedroS11** [comment]
I didn't try it with .net Framework but I know that Framework has wshttpbinding class that supports these operations. However, .net core team haven't developed that and already said they won't do it in the near future. This is so important when you need to do soap requests behind proxies. It's a common scenario if you work for a country company or with old systems like bank and health

**Comment by Lxiamail** [comment]
@PedroS11 
>>However, .net core team haven't developed that and already said they won't do it in the near future.
What specific feature that this refers to?

**Comment by HongGit** [comment]
@PedroS11 please let us know if this is still an issue.  We now support WSHttpBinding.   If this is still a feature request, feel free to reopen the issue.
