### ISSUE TITLE
Error: No type could be loaded for the value System.Collections.ObjectModel.ObservableCollection

### ISSUE THREAD

**Issue by acohenOT** [dotnet/wcf#4606]
Environment
- Windows 10 x64
- Visual Studio 2019 16.9.4
- Recreated with empty project created with `dotnet new classlib`
- Tried with target framework `net5.0` and `net4.8`. Same result.

Problem:
When creating a WCF service reference, on the Data Type Options screen, change Array to ObservableCollection. 

``Error: No type could be loaded for the value 'System.Collections.ObjectModel.ObservableCollection`1' passed to the --collectionType option. Ensure that the assembly this type belongs to is specified via the --reference option.``

See screenshots below.

I am able to create the service reference using System.Array. I then tried to change the collectionTypes in ConnectedService.json, but the error still occurs updating the reference.

```json
"collectionTypes": [
      "System.Collections.ObjectModel.ObservableCollection`1",
      "System.Collections.Generic.Dictionary`2"
    ],
```

I assume I need to set the `reference` parameter as the error indicates but there is very limited information on this json file so I cannot tell how to do this.

![image](https://user-images.githubusercontent.com/34688558/116022032-64c4a680-a617-11eb-9bb5-fc2e8845c2e3.png)
![image](https://user-images.githubusercontent.com/34688558/116022114-90479100-a617-11eb-80af-489abc4f1e7a.png)

**Comment by acohenOT** [comment]
Workaround:

- Change project `TargetFramework` to `netstandard2.1`. I cannot get this to work with `net5.0`.
- Add NuGet package `System.ObjectModel` to project

Now, when you go to add the WCF reference, change `Collection type` to `System.Collections.ObjectModel.ObservableCollection`, check `Reuse types in referenced assemblies`, select `Reuse types in specified referenced assemblies` and check `System.ObjectModel`.

![image](https://user-images.githubusercontent.com/34688558/119682695-17537900-be11-11eb-830d-dd8a5eb9b037.png)

Visual Studio is now able to generate `Reference.cs` a `ConnectedService.json` file that looks like this.

```json
{
  "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
  "Version": "15.0.40203.910",
  "ExtendedData": {
    "inputs": [
      "http://localhost:8002/"
    ],
    "collectionTypes": [
      "System.Collections.Generic.Dictionary`2",
      "System.Collections.ObjectModel.ObservableCollection`1"
    ],
    "messageContract": true,
    "namespaceMappings": [
      "*, MyNamesspace"
    ],
    "references": [
      "System.ObjectModel, {System.ObjectModel, 4.3.0}"
    ],
    "targetFramework": "netstandard2.1",
    "typeReuseMode": "Specified"
  }
}
```

**Comment by HongGit** [comment]
This should have been fixed in the latest version of dotnet-svcutil.exe and WCF Connected Services.

Feel free to reactivate if this is not the issue.

**Comment by Montago** [comment]
I just tried updating dotnet-svcutil to version 2.1.0 and it's still not able to update a WCF Service reference with ObservableCollection + Dictionary + Databinding

**Comment by Montago** [comment]
System.ObjectModel is .NET 5 and doesnt work so good in .NET 6 and 7
